postgres:
  image: postgres
  container_name: postgres
  privileged: true
  command: postgres
rubyapp:
  build: .
  container_name: ruby
  privileged: true
  volumes:
    - "~/projects/ruby:/app"
  ports:
    - "3000:3000"
  environment:
    - "db://postgres:@postgres/postgres"
  links:
    - postgres
