data:
  image: busybox
  container_name: data
  volumes:
    - "/root"
    - "/home"
    - "/share"
    - "$HOME:/host"
  privileged: true
test:
  build: test
  container_name: test
  volumes_from:
    - data
  privileged: true
  restart: always
