data:
  image: busybox
  container_name: data
  volumes:
    - "/home"
    - "/share"
  privileged: true
itamae:
  build: itamae
  container_name: itamae
  volumes:
    - "/home:/home"
    - "/share:/share"
    - "./itamae:/itamae"
  volumes_from:
    - data
  extra_hosts:
    - "localhost:127.0.0.1"
  privileged: true
  stdin_open: true
  tty: true
ci:
  build: ci
  container_name: ci
  volumes_from:
    - data
  extra_hosts:
    - "localhost:127.0.0.1"
  privileged: true
  stdin_open: true
  tty: true
web:
  build: web
  container_name: web
  volumes_from:
    - data
  ports:
    - "80:80"
    - "443:443"
  extra_hosts:
    - "localhost:127.0.0.1"
  privileged: true
  restart: always
samba:
  build: samba
  container_name: samba
  volumes_from:
    - data
  ports:
    - "445:445"
  privileged: true
  restart: always
