data:
  image: busybox
  container_name: data
  volumes:
    - "/root"
    - "/home"
    - "/share"
    - "$HOME:/host"
arch:
  build: archlinux
  container_name: arch
  volumes_from:
    - data
  privileged: true
  stdin_open: true
  tty: true
