elbacky_postgres:
  image: postgres
  container_name: elbacky_postgres
  privileged: true
  command: postgres
elbacky:
  build: .
  container_name: elbacky
  environment:
    - "DATABASE_URL:db://postgres:@postgres/postgres"
  privileged: true
  volumes:
    - "~/projects/elbacky:/app"
  ports:
    - "80:80"
  links:
    - elbacky_postgres
