che:
  image: codenvy/che:latest
  command: >
    bash -c "
    sudo rm -rf /home/user/che/lib-copy/* &&
    sudo rm -rf /home/user/che/tomcat/temp/local-storage/* &&
    mkdir -p /home/user/che/lib-copy/ &&
    sudo chown -R user:user /home/user/che &&
    cp -rf /home/user/che/lib/* /home/user/che/lib-copy &&
    /home/user/che/bin/che.sh run -d
    "
  net: "host"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/user/che/lib:/home/user/che/lib-copy"
    - "/home/user/che/workspaces:/home/user/che/workspaces"
    - "/home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage"
  container_name: che
  environment:
    - CHE_DOCKER_MACHINE_HOST=192.168.99.100
